name: asg


on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: json
    steps:
      - uses: actions/checkout@v3

      - name: Initialize backend
        working-directory: asg
        run: |
          terraform init


      - name: Configure workspace
        working-directory: asg
        run: |
          terraform workspace new us || terraform workspace select us
          terraform init



      - name: Run a Plan
        working-directory: asg
        run: |
          terraform plan
