name: rds


on:
  workflow_run:
    workflows: ["vpc"]
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: json
    steps:
      - uses: actions/checkout@v3

      - name: Initialize backend
        working-directory: rds
        run: |
          terraform init -reconfigure


      - name: Configure workspace
        working-directory: rds
        run: |
          terraform workspace new us || terraform workspace select us
          terraform init -reconfigure



      - name: Run a Plan
        working-directory: rds
        run: |
          terraform plan


      - name: Run a apply
        working-directory: rds
        run: |
          terraform destroy --auto-approve
